{ signal: [
  [ 'Command',
    [ 'MC',
      { name: "CK",   wave: "0101010101010101",                                       phase: 0, node:'.a.'  },
      { name: "CMD",  wave: "x..3x=x4x=x=x=x=x", data: "RAS NOP CAS NOP NOP NOP NOP", phase: 1 },
      { name: "ADDR", wave: "x..=x..=x........", data: "ROW COL",                     phase: 1 },
    ],
    {},
    [ 'DRAM',
      { name: "CK",   wave: "0101010101010101",                                       phase: -0.6, node:'.1.......b'  },
     { name: "CMD",  wave: "x..3x=x4x=x=x=x=x", data: "RAS NOP CAS NOP NOP NOP NOP", phase: 0.4 },
      { name: "ADDR", wave: "x..=x..=x........", data: "ROW COL",                     phase: 0.4 },
    ],
  ],
  {},{},
  [ 'DDR',
    ['DRAM',
      { name: "DQS",  wave: "z........0.1010z.", phase: -0.6, node:'...........2' },
      { name: "DQ",   wave: "z..........5555z.", data: "D0 D1 D2 D3", phase: -0.6 },
    ],
     {},
    ['MC',
      { name: "DQS",  wave: "z........0.1010z.", phase: -1.2 },
      { name: "DQ",   wave: "z..........5555z.", data: "D0 D1 D2 D3", phase: -1.2 },
    ],

  ],
  {},{},
  [ 'LPDDR',
    ['DRAM',
      { name: "DQS",  wave: "z........0.1010z.", phase: -0.0, node:'...........3' },
      { name: "DQ",   wave: "z..........5555z.", data: "D0 D1 D2 D3", phase: -0.0 },
    ],
    {},
    ['MC',
      { name: "DQS",  wave: "z........0.1010z.", phase: -0.6 },
      { name: "DQ",   wave: "z..........5555z.", data: "D0 D1 D2 D3", phase: -0.6 },
     
      { name: "DQS dly",  wave: "0..........1010..", phase: -1.4 },
      { name: "DQr capt",   wave: "x..........5.5.x.", data: "D0 D2", phase: -1.5 },
      { name: "DQf capt",   wave: "x...........5.5.x.", data: "D1 D3", phase: -1.5 },
    ],

  ],
],
   edge: ['a~>1 delay', 'b~>2 DQS aligned with CK', 'b~>3 DQS NOT aligned with CK'],
     config: {hscale:2},
   
}
